# Nameはモブの名前を入れてください。IDではないです　MMでDisplay: '&Cゴーストラベジャー' なら Name: '&Cゴーストラベジャー'
# text1はメッセージ欄に送信されるメッセージ
# text2はtext1にカーソル合わせたときに表示されるメッセージ
Mob:
  ghost_ravager:
    Name: "&cゴーストラベジャー"
    text1: "&f挑戦[&c悲痛なる叫び&f]を達成した"
    text2: "&cゴーストラベジャーを討伐した"
  ghost_goldmob:
    Name: "&e大富豪"
    text1: "&f挑戦[&e君はお金持ち&f]を達成した"
    text2: "&c大富豪から金を奪い取った"