name: MythicClearMessage
version: 1.0
main: MythicClearMessage.MythicClearMessage
api-version: 1.15
authors: [46kuri_]
description: MythicSubPlugin

commands:
  MythicClearMessage:
    description: MythicClearMessage Reload
    permission: MythicClearMessage.permission.Admin
  mcm:
    description: MythicClearMessage Reload
    permission: MythicClearMessage.permission.Admin
permissions:
  MythicClearMessage.permission.Admin:
    default: op
  MythicClearMessage.permission.Member:
    default: true